# Generated by Django 3.0.3 on 2020-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('sessionid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
