# Generated by Django 3.0.2 on 2020-02-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='unique_visits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='visits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
