# Generated by Django 3.0.2 on 2020-02-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200214_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='referral',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='unique_visits',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='visits',
        ),
        migrations.CreateModel(
            name='VisitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(blank=True, null=True)),
                ('visits', models.PositiveIntegerField(blank=True, null=True)),
                ('unique_visitors', models.ManyToManyField(blank=True, to='analysis.Visitor')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.Visitor'),
        ),
    ]
