# Generated by Django 3.0.2 on 2020-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200214_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='ip',
            new_name='visitor',
        ),
    ]
