# Generated by Django 3.0.2 on 2020-02-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200214_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('month_number', models.PositiveIntegerField()),
                ('domain', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='visitdata',
            name='visits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='UniqueVisitWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('week_number', models.PositiveIntegerField()),
                ('domain', models.URLField()),
                ('visit_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.VisitData')),
            ],
        ),
        migrations.AddField(
            model_name='visitdata',
            name='unique_week_visits',
            field=models.ManyToManyField(blank=True, to='analysis.UniqueVisitWeek'),
        ),
    ]
