# Generated by Django 3.0.2 on 2020-02-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200214_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquevisitmonth',
            name='visit_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.VisitData'),
        ),
    ]
