# Generated by Django 3.0.2 on 2020-02-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_uniquevisitmonth_visit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
