# Generated by Django 3.0.2 on 2020-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_referral_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdata',
            name='unique_month_visits',
            field=models.ManyToManyField(blank=True, to='analysis.UniqueVisitMonth'),
        ),
        migrations.CreateModel(
            name='BoxGuruVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unique_visitors', models.ManyToManyField(blank=True, to='analysis.Visitor')),
            ],
        ),
    ]
