# Generated by Django 3.0.2 on 2020-02-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20200214_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=2000)),
                ('status_code', models.IntegerField()),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('remote_addr_fwd', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.TextField()),
                ('cookies', models.TextField(blank=True, null=True)),
                ('get', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('raw_post', models.TextField(blank=True, null=True)),
                ('is_secure', models.BooleanField()),
                ('is_ajax', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='boxguruvisit',
            name='unique_visitors',
        ),
        migrations.RemoveField(
            model_name='boxguruvisit',
            name='visits',
        ),
        migrations.AddField(
            model_name='boxguruvisit',
            name='number_of_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxguruvisit',
            name='reached_referral',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boxguruvisit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.Session'),
        ),
        migrations.AddField(
            model_name='boxguruvisit',
            name='visitor',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.URLField()),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.BoxGuruVisit')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.URLField()),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.BoxGuruVisit')),
            ],
        ),
        migrations.CreateModel(
            name='BoxGuruVisitTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unique_month_visits', models.ManyToManyField(blank=True, to='analysis.UniqueVisitMonth')),
                ('unique_visitors', models.ManyToManyField(blank=True, to='analysis.Visitor')),
                ('unique_week_visits', models.ManyToManyField(blank=True, to='analysis.UniqueVisitWeek')),
            ],
        ),
    ]
