# Generated by Django 3.0.2 on 2020-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20200214_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeOneLande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landed', models.BooleanField()),
            ],
        ),
    ]
