# Generated by Django 3.0.2 on 2020-02-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_someonelande'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SomeOneLande',
            new_name='SomeOneLanded',
        ),
    ]
