# Generated by Django 3.0.2 on 2020-02-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20200214_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='someonelanded',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
