# Generated by Django 3.0.2 on 2020-02-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_someonelanded_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequest',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.Session'),
        ),
    ]
