# Generated by Django 2.2.6 on 2019-10-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Box type')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=120, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_dim1', models.PositiveIntegerField(null=True, verbose_name='Inner width (mm)')),
                ('inner_dim2', models.PositiveIntegerField(null=True, verbose_name='Inner length (mm)')),
                ('inner_dim3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Inner height (mm)')),
                ('outer_dim1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Outer width (mm)')),
                ('outer_dim2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Outer length (mm)')),
                ('outer_dim3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Outer height (mm)')),
                ('inner_var_dim_MIN', models.PositiveIntegerField(blank=True, null=True, verbose_name='Inner variable dimension min (mm)')),
                ('inner_var_dim_MAX', models.PositiveIntegerField(blank=True, null=True, verbose_name='Inner variable dimension max (mm)')),
                ('outer_var_dim_MIN', models.PositiveIntegerField(blank=True, null=True, verbose_name='Outer variable dimension min (mm)')),
                ('outer_var_dim_MAX', models.PositiveIntegerField(blank=True, null=True, verbose_name='Outer variable dimension max (mm)')),
                ('diameter', models.PositiveIntegerField(blank=True, verbose_name='Diameter (mm)')),
                ('bottles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of bottles')),
                ('standard_size', models.CharField(blank=True, max_length=5, null=True, verbose_name='Standard size')),
                ('description', models.CharField(blank=True, default='', max_length=120, verbose_name='Product description')),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('minimum_purchase', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bundle size')),
                ('url', models.URLField(blank=True, max_length=120, verbose_name='URL')),
                ('company', models.CharField(max_length=120, verbose_name='Company')),
                ('price_ex_BTW', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Price/box ex. BTW')),
                ('price_incl_BTW', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Price/box incl. BTW')),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BoxType')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Color')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='WallThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_thickness', models.CharField(blank=True, choices=[('SW', 'Single wall'), ('DW', 'Double wall'), ('TW', 'Triple wall'), ('CB', 'Solid cardbord wall')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TierPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(null=True, verbose_name='Tier')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price/box ex. BTW')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120, verbose_name='Tag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductModel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='wall_thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.WallThickness'),
        ),
    ]
