# Generated by Django 3.0.3 on 2020-02-25 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Liked by'),
        ),
        migrations.AddField(
            model_name='product',
            name='wall_thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.WallThickness', verbose_name='Wall-thickness'),
        ),
    ]
