# Generated by Django 3.0.2 on 2020-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='id',
            field=models.AutoField(auto_created=True, default=100000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='id',
            field=models.AutoField(auto_created=True, default=1000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='category_id',
            field=models.IntegerField(blank=True, verbose_name='Category id'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type_id',
            field=models.IntegerField(blank=True),
        ),
    ]
