# Generated by Django 2.2.6 on 2019-10-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191016_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='box_type',
        ),
        migrations.DeleteModel(
            name='BoxType',
        ),
    ]
