# Generated by Django 3.0.2 on 2020-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200201_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='category_url',
            field=models.CharField(max_length=120, null=True, verbose_name='URL-naam'),
        ),
    ]
