# Generated by Django 2.2.6 on 2019-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191016_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Diameter (mm)'),
        ),
    ]
