# Generated by Django 2.2.6 on 2019-11-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttype_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='main_category',
        ),
    ]
