# Generated by Django 2.2.6 on 2019-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191016_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='wallthickness',
            name='wall_thickness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
