# Generated by Django 2.2.6 on 2019-10-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191016_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wall_thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.WallThickness'),
        ),
    ]
