# Generated by Django 2.2.6 on 2019-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191016_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='blank', max_length=120, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='blank', max_length=120, verbose_name='Product type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='wall_thickness',
            field=models.CharField(default='blank', max_length=120, verbose_name='Wall thickness'),
            preserve_default=False,
        ),
    ]
