# Generated by Django 2.2.6 on 2019-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttype_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='category',
            field=models.CharField(max_length=120, null=True, verbose_name='Hoofdcategorie'),
        ),
    ]
