# Generated by Django 2.2.6 on 2019-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191211_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['inner_dim1'], 'permissions': (('can_see_all_liked_products', 'Get list of liked products'), ('create_update_delete', 'Create/update/delete products')), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='products.ProductType'),
        ),
    ]
