# Generated by Django 2.2.6 on 2019-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191016_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=120, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=120, null=True, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wall_thickness',
            field=models.CharField(max_length=120, null=True, verbose_name='Wall thickness'),
        ),
    ]
