# Generated by Django 2.2.6 on 2020-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191212_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
