# Generated by Django 2.2.6 on 2020-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200116_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Volume'),
        ),
    ]
