# Generated by Django 2.2.6 on 2020-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200116_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='type_singular',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Product Type Singular'),
        ),
    ]
