# Generated by Django 2.2.6 on 2019-10-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191017_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type', 'inner_dim1'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wall_thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.WallThickness'),
        ),
    ]
