# Generated by Django 2.2.6 on 2019-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191017_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierprice',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='price_table',
            field=models.ManyToManyField(null=True, to='products.TierPrice'),
        ),
    ]
