# Generated by Django 2.2.6 on 2019-10-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191017_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='products.Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_table',
            field=models.ManyToManyField(to='products.TierPrice'),
        ),
    ]
