# Generated by Django 2.2.6 on 2019-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191017_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallthickness',
            name='wall_thickness',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
