# Generated by Django 2.2.6 on 2019-10-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191018_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=120, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tierprice',
            name='tier',
            field=models.PositiveIntegerField(verbose_name='Tier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallthickness',
            name='wall_thickness',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
